name: Build
on:
  workflow_dispatch:
  push:
    branches-ignore:
      'l10n_1.19/dev'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    env:
      ITHUNDXRMAVENUSERNAME: ${{ secrets.ITHUNDXRMAVENUSERNAME }}
      ITHUNDXRMAVENPASSWORD: ${{ secrets.ITHUNDXRMAVENPASSWORD }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send Building Notification to Discord
        if: github.event_name != 'pull_request'
        uses: realRobotix/action-discord-notifier@release-master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message-title: "Building mod from ${{ github.ref }}"

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Collect built jars
        run: ./gradlew moveBuiltJars

      - name: Capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: jars

      - name: Upload Production builds to Discord
        if: github.event_name != 'pull_request'
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ./jars/*.jar