name: Build Forge Release

on:
  workflow_dispatch:
    inputs:
      create_forge_version:
        description: Create forge dependency version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CREATE_FORGE_VER: ${{ github.event.inputs.create_forge_version }}
      RELEASE_BUILD: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Forge & Publish to Maven
        env:
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        run: ./gradlew :forge:build :forge:publish

      - name: Upload Mod to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew :forge:modrinth

      - name: Upload Mod to Curseforge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        run: ./gradlew :forge:publishCurseForge